const actions = {
  // SESSION
  LOGIN: "session/LOGIN",
  LOGOUT: "session/LOGOUT",
  FETCH_SESSION: "session/FETCH_SESSION",
  SET_SESSION_STATE: "session/SET_SESSION_STATE",

  // OVERVIEW
  SET_OVERVIEW_STATE: "overview/SET_OVERVIEW_STATE",
  FETCH_OVERVIEW: "overview/FETCH_OVERVIEW",
  FILTER_OVERVIEW: "overview/FILTER_OVERVIEW",

  // REPORTS
  SET_REPORT_STATE: "reports/SET_REPORT_STATE",
  SET_REPORT_DATE: "reports/SET_REPORT_DATE",
  FETCH_REPORTS: "reports/FETCH_REPORTS",
  FETCH_REPORT_FORM_DATA: "reports/FETCH_REPORT_FORM_DATA",

  // VENDORS
  SET_VENDOR_STATE: "vendors/SET_VENDOR_STATE",
  FETCH_VENDORS: "vendors/FETCH_VENDORS",
  CREATE_VENDOR: "vendors/CREATE_VENDOR",
  UPDATE_VENDOR: "vendors/UPDATE_VENDOR",
  DELETE_VENDOR: "vendors/DELETE_VENDOR",

  // PRODUCTS
  SET_PRODUCT_STATE: "products/SET_PRODUCT_STATE",
  FETCH_PRODUCTS: "products/FETCH_PRODUCTS",

  // NAVIGATOR
  SET_NAVIGATOR_STATE: "navigator/SET_NAVIGATOR_STATE",
  NAVIGATE: "navigator/NAVIGATE",
}

export default actions
