const actions = {
  // SESSION
  LOGIN: 'session/LOGIN',
  LOGOUT: 'session/LOGOUT',
  FETCH_SESSION: 'session/FETCH_SESSION',
  SET_SESSION_STATE: 'session/SET_SESSION_STATE',

  // OVERVIEW
  SET_OVERVIEW_STATE: "overview/SET_OVERVIEW_STATE",
  FETCH_OVERVIEW: "overview/FETCH_OVERVIEW",
  FILTER_OVERVIEW: "overview/FILTER_OVERVIEW",

  // REPORTS
  SET_REPORT_STATE: "reports/SET_REPORT_STATE",
  SET_REPORT_DATE: "reports/SET_REPORT_DATE",
  FETCH_REPORTS: "reports/FETCH_REPORTS",
  FETCH_REPORT_FORM_DATA: "reports/FETCH_REPORT_FORM_DATA",

  // VENDORS
  SET_VENDOR_STATE: "reports/SET_VENDOR_STATE",
  FETCH_VENDORS: "reports/FETCH_VENDORS",

  // PRODUCTS
  SET_PRODUCT_STATE: "reports/SET_PRODUCT_STATE",
  FETCH_PRODUCTS: "reports/FETCH_PRODUCTS",

  // NAVIGATOR
  SET_NAVIGATOR_STATE: 'navigator/SET_NAVIGATOR_STATE',
  NAVIGATE: 'navigator/NAVIGATE',
}

export default actions
